import { useEffect } from 'react'
import { Zap } from 'lucide-react'
import { usePolling } from '../hooks/usePolling'
import { fetchSignals } from '../services/api'
import Badge from '../components/common/Badge'
import LoadingSpinner from '../components/common/LoadingSpinner'
import EmptyState from '../components/common/EmptyState'

function StrengthBar({ value = 0 }) {
  const pct = Math.round(Math.min(1, Math.max(0, value)) * 100)
  const color = pct >= 70 ? 'bg-emerald-500' : pct >= 40 ? 'bg-yellow-500' : 'bg-red-500'
  return (
    <div className="flex items-center gap-2">
      <div className="flex-1 bg-slate-700 rounded-full h-1.5 w-20">
        <div className={`h-1.5 rounded-full ${color}`} style={{ width: `${pct}%` }} />
      </div>
      <span className="text-xs text-slate-400 w-8 text-right">{pct}%</span>
    </div>
  )
}

export default function Signals() {
  const { data, loading, refetch } = usePolling(fetchSignals, 8000)

  useEffect(() => {
    window.addEventListener('dashboard-refresh', refetch)
    return () => window.removeEventListener('dashboard-refresh', refetch)
  }, [refetch])

  const signals = data?.signals ?? []

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-xs text-slate-500">
          {data?.total ?? 0} signals generated by the ensemble model
        </p>
      </div>

      <div className="bg-card overflow-hidden">
        {loading ? <LoadingSpinner label="Loading signals…" /> :
         !signals.length ? (
           <EmptyState
             title="No signals yet"
             message="Signals appear here once the bot has run an analysis cycle."
             icon={Zap}
           />
         ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead className="bg-slate-800/60">
                <tr className="text-slate-400">
                  {['ID','Symbol','Type','Direction','Strength','Executed','Timestamp','Details'].map(h => (
                    <th key={h} className="px-4 py-3 text-left font-medium whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {signals.map(s => (
                  <tr key={s.id} className="hover:bg-slate-700/30 transition-colors">
                    <td className="px-4 py-3 font-mono text-slate-500">#{s.id}</td>
                    <td className="px-4 py-3 font-semibold text-white">{s.symbol}</td>
                    <td className="px-4 py-3"><Badge label={s.signal_type} /></td>
                    <td className="px-4 py-3"><Badge label={s.direction} /></td>
                    <td className="px-4 py-3"><StrengthBar value={s.strength} /></td>
                    <td className="px-4 py-3">
                      {s.executed
                        ? <Badge label="Executed" variant="filled" />
                        : <Badge label="Skipped"  variant="expired" />}
                    </td>
                    <td className="px-4 py-3 font-mono text-slate-400 whitespace-nowrap">
                      {s.timestamp ? new Date(s.timestamp).toLocaleString() : '—'}
                    </td>
                    <td className="px-4 py-3 text-slate-400 max-w-xs truncate" title={s.details}>
                      {s.details || '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
